services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    networks:
      - app_network

  my_bot:
    build: ./bot
    container_name: bot
    restart: always
    volumes:
      - db_data:/data
    networks:
      - app_network

  my_site:
    build: ./site
    container_name: site
    stop_signal: SIGKILL
    restart: always
    networks:
      - app_network

  api:
    build: ./api
    container_name: api
    restart: always
    volumes:
      - db_data:/data
    networks:
      - app_network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: always
    networks:
      - app_network
    environment:
      - NGROK_AUTHTOKEN=
    command:
      - http
      - nginx:80

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
