server {
    listen 80;
    server_name _; # Принимать запросы с любым Host-заголовком

    location / {
        proxy_pass http://site:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
    }
}

